runtime: python37
entrypoint: gunicorn -b :8080 WebFront.wsgi
handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

instance_class: F4

env_variables:
  CLOUDSQL_CONNECTION_NAME: propane-ground-269323:us-east1:spotify-instance
  CLOUDSQL_DATABASE_NAME: SPOTIFY
  CLOUDSQL_USERNAME: teameleven
  CLOUDSQL_PASSWORD: dbpassword

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
